version: "3.1"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ACCESS_SECRET}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  adminer:
    build:
      context: https://raw.githubusercontent.com/laradock/laradock/master/adminer/Dockerfile
    ports:
      - 8081:8080
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=mysql